### ISSUE TITLE
Protobuf parsing error

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#1]
import openapiart

openapiart.OpenApiArt(
    api_files=['C:/Users/rangabar.KEYSIGHT/Documents/GitHub/models/api/api.yaml'],  #--> snappi models
    python_module_name='throttle', 
    output_dir='./artifacts',
    protobuf_file_name='throttle'
)

################### info.yaml #################
openapi: 3.1.3

info:
  title: Open Traffic Generator API
  description: |-
    The Open Traffic Generator API consists of the following features:
    - a common Traffic Generator API
    - an Advanced Metrics API feature (under review)

    Contributions can be made in the following ways:
    - [open an issue](https://github.com/open-traffic-generator/models/issues) in the models repository
    - [fork the models repository](https://github.com/open-traffic-generator/models) and submit a PR
  version: 0.4.0
  contact:
    url: https://github.com/open-traffic-generator/models
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  x-model-guide: https://github.com/open-traffic-generator/models/blob/master/MODEL-GUIDE.md

servers: 
  - url: /

paths: {}

####################################

------------------------------------error output-----------------------------------
grpc_tools.protoc args: C:\Users\rangabar.KEYSIGHT\Desktop\snappi_env\openapiart\Scripts\python.exe -m grpc_tools.protoc --python_out=C:\Users\rangabar.KEYSIGHT\Desktop\openapiart\artifacts\throttle --grpc_python_out=C:\Users\rangabar.KEYSIGHT\Desktop\openapiart\artifacts\throttle --proto_path=C:\Users\rangabar.KEYSIGHT\Desktop\openapiart\artifacts throttle.proto
throttle.proto:4464:175: Expected ";".
throttle.proto:12971:26: Missing field number.
throttle.proto:12986:18: Missing field number.
throttle.proto:13001:24: Missing field number.
throttle.proto:13016:20: Missing field number.
throttle.proto:13031:26: Missing field number.
throttle.proto:13036:29: Missing field number.
throttle.proto:13048:24: Missing field number.
throttle.proto:13059:26: Missing field number.

openapiart generation throws protobuf parsing error.

--------------------------------------------------------------------------------------

**Comment by ajbalogh** [comment]
Hi @Rangababu-R, please ensure you are including all top level files and you are using the latest version 0.0.26 - in this case the info.yaml is missing.

```
openapiart.OpenApiArt(
    api_files=[
        'C:/Users/rangabar.KEYSIGHT/Documents/GitHub/models/api/api.yaml'
        'C:/Users/rangabar.KEYSIGHT/Documents/GitHub/models/api/info.yaml'
    ], 
    python_module_name='throttle',
    output_dir='./artifacts',
    protobuf_file_name='throttle',
    protobuf_package_name='throttle'
)
```
