### ISSUE TITLE
Placeholder issue for ENUMs requiring use of package name

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#128]
Currently, we have to use package name to access enum.

```go
	d1Bgp := d1Ip.Bgpv4().
		SetName("d1Bgp").
		SetDutAddress("1.1.1.2").
		SetRouterId("1.1.1.1").
		SetAsNumber(1111).
		SetAsType(gosnappi.DeviceBgpv4AsType.IBGP)
```

I understand that this maybe the best approach, but awaiting customer feedback if it matters to them (since initial argument for having a fluent interface was not having to require using package names)

**Comment by Rangababu-R** [comment]
@ashutshkumr can we close this?

**Comment by ashutshkumr** [comment]
Not going to be addressed
