### ISSUE TITLE
Cannot set column names in metrics request

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#130]
Although I found this specifically in snappi, but @ANISH-GOTTAPU @Rangababu-R we need to understand how we can find such issues.

BGPv4 metrics allows setting device names but not column names.

```go
req := api.NewMetricsRequest()
// works
req.Bgpv4().SetDeviceNames()

// does not work
req.Bgpv4().SetColumnNames()
```

**Comment by ajbalogh** [comment]
This shouldn't be something you have to find on an individual basis. 
This is a type of generation that isn't complete.  Specifically type: array, items: string, enums: [...]
