### ISSUE TITLE
FromYaml()/FromJson() ignores bad key/value

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#155]
Following throws error, as expected.

```go
config.FromYaml("svdfjvdljfv")
```

Following does not throw any error:

```go
config.FromYaml("hello:")
```

Check the same for FromJson() too.

**Comment by alakendu** [comment]
We can achieve it using DiscardUnknown:false

```go
func (obj *config) FromJson(value string) error {
	opts := protojson.UnmarshalOptions{
		AllowPartial:   true,
		DiscardUnknown: false,
	}
	return opts.Unmarshal([]byte(value), obj.msg())
}
```
Currently I am getting following error after execution of these code

```go
local_cnf := `{"num":6.13,"strs":["a","b"]}`
err := config.FromJson(local_cnf)
fmt.Println("err ", err)
```

```
err  proto: (line 1:2): unknown field "num"
```

Please let me know if this will fulfil the requirement without regression.

**Comment by ajbalogh** [comment]
I don't think validation shouldn't take place in this routine.
What is wrong with ignoring bad keys?
For bad values there needs to be separate validation logic that is being tracked in a separate issue.

**Comment by ashutshkumr** [comment]
While reviewing this piece, here are my thoughts:
- This issue just tracks validation of JSON/YAML; e.g. it should raise any issue with bad syntax (which is implicitly done) and bad form (e.g. provide bad keys, provide values with bad type, do not provide value at all)
- The reason it makes sense to do it in this routine because once we're past this routine, we don't have access to JSON/YAML anymore. Moreover, this is something native unmarshaller should take care of.
- Currently we initialize unmarshaller inside every `From*` func; Is there any specific reason to do that ? Since we should just initialize one unmarshaller globally (for each text format)

**Comment by ajbalogh** [comment]
Having a specific marshal/unmarshal at every object level allows for partial fragments to be created/set.

**Comment by alakendu** [comment]
basic validation already taken care and added UT for it.
