### ISSUE TITLE
Not able to extract warnings from successful response returned from SetConfig call

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#161]
I am able to extract metrics, but not warnings from successful call to SetConfig. Tested with snippet below.

```go
package main

import (
	"log"

	"github.com/open-traffic-generator/snappi/gosnappi"
)

func main() {
	api := gosnappi.NewApi()
	api.NewGrpcTransport().SetLocation("host:30043")

	cfg := newConfig(api)
	resp, err := api.SetConfig(cfg)
	if err != nil {
		log.Fatal(err)
	}

	log.Println(resp.ToYaml())

	req := api.NewMetricsRequest()
	req.Port()
	r2, err := api.GetMetrics(req)
	if err != nil {
		log.Fatal(err)
	}
	for _, m := range r2.PortMetrics().Items() {
		log.Println(m.Name())
	}

}

func newConfig(api gosnappi.GosnappiApi) gosnappi.Config {
	cfg := api.NewConfig()
	cfg.Ports().Add().SetName("p1").SetLocation("service-ixia-c-port1.ixia-c:5555")
	f := cfg.Flows().Add()
	f.SetName("f1").TxRx().Port().SetTxName("p1")
	return cfg
}
```

**Comment by ANISH-GOTTAPU** [comment]
Not able to see errors also:
```
func TestResponseError(t *testing.T) {
	api := gosnappi.NewApi()
	grpc := api.NewGrpcTransport()
	grpc.SetLocation(mockGrpcServerLocation).SetRequestTimeout(10000)
	config := api.NewConfig()
	p1 := config.Ports().Add()
	p1.SetName("port1").SetLocation("service-ixia-c-port1.ixia-c.svc.cluster.local:5555")
	p2 := config.Ports().Add()
	p2.SetName("port2").SetLocation("service-ixia-c-port2.ixia-c.svc.cluster.local:5555")
	f1 := config.Flows().Add().SetName("f1")
	f2 := config.Flows().Add().SetName("f2")
	f1.TxRx().Port().SetTxName(p1.Name()).SetRxName(p2.Name())
	f2.TxRx().Port().SetTxName(p1.Name()).SetRxName(p2.Name())
	resp, err := api.SetConfig(config)
	log.Print(resp, err)
}
```

=========================================
**Expected the error response but got null**
=== RUN   TestResponseError
2021/09/01 19:02:44 <nil> null

===========================================
**The logs on the server shows Error 500**
2021-09-01 12:56:06,367 : Requesting set_config ...
2021-09-01 12:56:06,517 : Snappi_api Setconfig Returned Exception :  Exception(500, {'errors': ['Error occurred while setting Traffic config for user common:Cumulative percent line rate 200 is greater than 100 percent for port "port1"']})
2021-09-01 12:56:06,517 : Returning status_code_500 to client

**Comment by ANISH-GOTTAPU** [comment]
just to add on, got the response error if HTTPTransport is used instead of gRPC

=== RUN   TestResponseError
2021/09/01 19:56:30 <nil> {"errors":["Error occurred while setting Traffic config for user common:Cumulative percent line rate 200 is greater than 100 percent for port \"port1\""]}
--- PASS: TestResponseError (4.12s)
