### ISSUE TITLE
int64 type is not handled in protobuf and causing validation issue in go

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#176]
**Version information**
version: 0.1.8

**Describe the bug**
In the implementation of go SDK validation part, noticed the min and max values of an object is of range greater than int32.
After the generation go lint throws an error with invalid type.

**To Reproduce**
if the min and max values from openapi model are greater than the int32 range.

**Expected behavior**
when the format in the model is int64 and the min or max value range is greater that int32, protobuf and openapiartgo.py shall generate int64 typed structs and returns.

**Additional context**
Debugged and noticed that the int64 type is not handled while generating the proto file.

**Comment by alakendu** [comment]
fix should available 0.1.11
