### ISSUE TITLE
FromJson() method in gosnappi should return error/errors instead of panic and exit the app

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#206]
**Is your feature request related to a use case? Please describe.**
When using `gosnappi` as part of HTTP server, we don't want deserializer to panic and exit in between.

**Describe the solution you'd like**

This probably won't break existing scripts as currently users don't check the return value of `From*` funcs.
Things will break if we start to align behavior of `To*` funcs, to keep the two kinds of funcs consistent.

```go
config := api.NewConfig()
if err := config.FromJson(`{"ports": [], "flows": []}`); err != nil {
    // do something
}
```

**Describe alternatives you've considered**
Recovering from panics. It requires spawning goroutines which is really sub-optimal.
https://go.dev/blog/defer-panic-and-recover

**Additional context**

**Comment by ajbalogh** [comment]
available in v0.1.20
