### ISSUE TITLE
Should generated funcs for API calls be methods on relevant struct types ?

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#213]
**NOTE**: This is just a brain dump from discussion that happened during sprint 6 demo. Please feel free to correct or add more comments. The idea is to understand the core requirement and see how we can address it the best possible way.

This came up while discussing `SetRouteState` API with Marcus and team. The exact concern was:

> Why do we have yet another top level API for withdrawing or advertising routes ? Why can't we just go to a specific route object and call a method on it to withdraw or advertise routes ?

An argument *for above* quoted by Marcus and team was:
- Current `SetRouteState` API does not seem very similar to how a network engineer would execute it on a real device

An argument *against above* acknowledged by Marcus and team was:
- Top level `SetRouteState` allows for batch operation on all kinds of routes

*Misc* observations from the discussion:
- Batch operation for `SetTransmitState` does make sense, so should we end up having some API calls as top level funcs and some API calls as method on corresponding objects ?
- In context of batch operation for `SetRouteState`, what's **more of a priority** is that we should be able to calculate the duration for dynamically triggered events (since a cluster could consist of more than one node, we need to have a mechanism for start/end timestamps to be synced throughout the cluster).
- In both the approaches mentioned above, user will have to deal with the config object hierarchy
- It may be a "slight surprise" to network engineers accustomed to openconfig to see that state change is not really reflected in the config but has to be queried using `get_metrics` API.

- What can we do to keep the API surface for OTG small, what else do we plan to expose in future ?

**Comment by Rangababu-R** [comment]
@ashutshkumr can this issue be closed?

**Comment by ashutshkumr** [comment]
Not going to be addressed
