### ISSUE TITLE
GoSnappi: FromJson should return all the errors, right now just returning the first

### ISSUE THREAD

**Issue by rudranil-das** [open-traffic-generator/openapiart#222]
Observation from snappi-version: 0.6.5

Use-case: 
From server-side implementation (e.g. ixia-c controller), end-user would expect all the validation/syntax/construct errors to be returned at one go in response to an API call, instead of one at a time.

As gosnappi is being used as a server-side skeleton generator in ixia-c and expected to provide the aforementioned errors, this should be supported.

To illustrate with an example, please consider the following input json to FromJson of gosnappi.Config
```
{
  "ports": [
    {
      "location": "10.39.32.156:5555",
      "name": "p1"
    },
    {
      "location": "10.39.32.156:5556",
      "name": "p2"
    }
  ],
  "layer1": [
        {
            "name": "l1",
            "port_names": ["p1", "p2"],
            "speed": "speed_1_gbps"
        }
  ],
  "flows": [
    {
      "name": "flw",
      "tx_rx": {
        "port": {
          "TX_NAME": "p1",
          "rx_name": "p2"
        },
        "choice": "port"
      },
      "size": {
        "fixed": 128,
        "choice": "SIZE-CHOICE"
      },
      "metrics": {
        "enable": true
      },
      "duration": {
        "choice": "DURATION-CHOICE",
        "fixed_packets": {
          "packets": 1000
        }
      },
      "rate": {
        "choice": "RATE-CHOICE",
        "pps": 100
      },
      "packet": [
        {
          "ethernet": {},
          "choice": "ethernet"
        }
      ]
    }
  ]
}
```

The output from FromJson is
```
"proto: (line 24:11): unknown field \"TX_NAME\""
```

It should also return error for invalid choice values for size, duration, rate as well as they are also invalid
(example above is just for illustration, errors can be of any possible type as identifiable by gosnappi)

**Comment by Rangababu-R** [comment]
proto json un-marshal will not return a list of errors. So will not be fixing anything
