### ISSUE TITLE
gosnappi helper `Items()` for iterators needs to be more efficient

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#230]
**Version information**
https://github.com/open-traffic-generator/openapiart/releases/tag/v0.1.22

**Describe the bug**
As of today, everytime `.Items()` is called on an iterator, we create a list of object wrappers and return it.

```go
func (obj *metricsPortMetricIter) Items() []PortMetric {
	slice := []PortMetric{}
	for _, item := range obj.obj.obj.Ports {
		slice = append(slice, &portMetric{obj: item})
	}
	return slice
}
```

**Expected behavior**
Given the fact that this is the most common way for processing each item in the iterator, we should cache the wrapper list to avoid GC pressure and additional processing when `.Items()` is called.

**Comment by alakendu** [comment]
Issue should fix in https://github.com/open-traffic-generator/openapiart/releases/tag/v0.1.25
