### ISSUE TITLE
Validation doesn't happen for negative integer, negative float, float in min-max range 

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#240]
**Version information**
0.1.24

**Describe the bug**
Validation is not happening for below 
1) Negative Integer
2) Negative Float
3) Float in min-max Range
4) List of Integers with negative value
5) List of Float with negative values

**To Reproduce**
```
func TestConfigGeneratedValidate(t *testing.T) {
	api := openapiart.NewApi()
	config := api.NewPrefixConfig()
	config.SetSpace1(-11).SetFullDuplex100Mb(-11).SetB(-100.11).SetC(-11).SetListOfIntegerValues([]int32{-1, -2, -3}).SetInteger64(-10000000000000000)
	v1 := config.RequiredObject()
	v1.SetEA(-100.11).SetEB(-1.7976931348623157e+308)
	assert.NotNil(t, v1.Validate())
```

**Expected behavior**
Validation should happen and errors need to be returned

**Comment by Rangababu-R** [comment]
will be available in 0.1.26
