### ISSUE TITLE
FromJson() accepts empty string but does not initialize objects to defaults resulting in nil pointer error on accessing getter

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#247]
**Version information**
0.1.26

**Describe the bug**
FromJson() accepts empty string but does not initialize objects to defaults. This breaks objects containing choice because when accessing choice getter, none of the choices are set.

**To Reproduce**
This will raise nil pointer error.
```go
	r := api.NewMetricsRequest()
	r.FromJson("")
	fmt.Println(r.Choice())
```

**Expected behavior**
nil pointer error shouldn't be raised, in fact the object should be initialized to defaults.

**Comment by Rangababu-R** [comment]
available in 0.1.31
