### ISSUE TITLE
"servergen" branch should compatible with Python2

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/openapiart#256]
**Version information**
https://github.com/open-traffic-generator/openapiart/tree/servergen

**Describe the bug**
Several section within this branch not compatible with python2.7. 

**To Reproduce**
This branch will break our CICD

**Expected behavior**
Openapiart should compiled with Python2 and Python3

**Additional context**
NA

**Comment by ajbalogh** [comment]
I think this should not be the case. We should strive to write current code and not target obsolete versions. Lets look at modifying CICD pipelines so that they run using current supported versions of python.
