### ISSUE TITLE
No validation for int and float types

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#275]
**Version information**
0.1.31

**Describe the bug**
Validation has been removed for int and float types.

**To Reproduce**
Any int or float type required property is not being validated

**Expected behavior**

**Additional context**
This needs to add back once the required property is generated as pointer

**Comment by ashutshkumr** [comment]
Duplicate of https://github.com/open-traffic-generator/openapiart/issues/232
