### ISSUE TITLE
Object type, required property is not being validated

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#276]
**Version information**
0.1.31

**Describe the bug**
The Object type property is not being validated, instead the default object is being created

**To Reproduce**
do not initialize the object property and try to validate, the required property will not raise a validation error 

**Expected behavior**
an error needs to be raised for the object type property.

**Additional context**
As there was no setter method in snappi the validation is creating the new object for the object typed properties.

**Comment by Vibaswan** [comment]
This feature is already taken care of in a previous merge 
#433
