### ISSUE TITLE
Unable to set empty string or 0 integer value for required field

### ISSUE THREAD

**Issue by jkristia** [open-traffic-generator/openapiart#288]
It is currently not possible to set a value of "" (empty string) or 0 for an for an integer on a required field.
object.FromJson(json data) returns error

```
func (ctrl *propertiesController) SetPropertyData(w http.ResponseWriter, r *http.Request) {
	var item models.PropertySetDataRequest
	if r.Body != nil {
		body, _ := ioutil.ReadAll(r.Body)
		if body != nil {
			item = models.NewPropertySetDataRequest()
			err := item.FromJson(string(body)) <-- ERROR returned if string is empty or integer is 0
			if err != nil {
				item = nil
			}
		}
	}
```
Work around is to **not** mark the field as required.

**Comment by ajbalogh** [comment]
I disagree with the proposed change. 
Required fields should remain as required as there is a discrepancy between openapi.yaml and the generated .proto and documenting a field as required but marking it as optional only confuses those looking at the .proto file.

The underlying generated fluent wrapper should account for required fields being set/not set, using some internal approach of marking required fields as dirty/not set/touched etc.
