### ISSUE TITLE
Optimize require serialize input to JSON and deserialize it back to protobuf in gRPC client 

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/openapiart#296]
**Version information**
https://github.com/open-traffic-generator/openapiart/releases/tag/v0.1.35

**Describe the bug**
We are serialize input to JSON and deserialize it back to protobuf in gRPC client .

```python
    def _serialize_payload(self, payload):
        if not isinstance(payload, (str, dict, OpenApiBase)):
            raise Exception("We are supporting [str, dict, OpenApiBase] object")
        if isinstance(payload, OpenApiBase):
            payload = payload.serialize()
        if isinstance(payload, dict):
            payload = json.dumps(payload)
        return payload
```
We need to optimize it.

**To Reproduce**
NA

**Expected behavior**
change snappi object to pb2 object 

**Additional context**
NA

**Comment by ashutshkumr** [comment]
Not going to be addressed
