### ISSUE TITLE
Numbers are serialized as strings

### ISSUE THREAD

**Issue by thomas-am** [open-traffic-generator/openapiart#315]
**Version information**
0.1.34

**Describe the bug**
Numbers are serialized as strings

**To Reproduce**
```
print (metrics_resp.num.__class__)
# <class 'int'>
serialized = metrics_resp.serialize()
print (serialized)
# BUG: there shouldn't be any quotes around "123"
# {
#   "num": "123"
# }
```

**Expected behavior**
Numbers should be serialized as numbers, not strings.

**Comment by Rangababu-R** [comment]
integer is purposefully encoded/decoded, to/from string if the format is int64 from the models (to match with grpc). 
could you please check the "num" field format from the models. or point me to the field node.

**Comment by ashutshkumr** [comment]
Expected behavior for large numbers.
