### ISSUE TITLE
grpcio-tools installation fails in 2.7

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#316]
**Version information**
0.1.42

**Describe the bug**
grpcio-tools fails to install in python2.7 env, the latest version of grpcio-tools seems to fail and any version which is less than 1.40 seems to be ideal for python2.7. currently tested with 1.35.0 which works locally.
Why CICD doesn't catch:
- In snappi actions the last version of grpcio-tools picked was 1.39.0 (ran 21 hours ago <took while creating this issue>)
- In Openapiart the last version was 1.39.0 (ran 7days ago <took while creating this issue>)
- In snappi-ixnetwork with snappi version(0.7.17) was 1.41.1 (ran 1 hour ago)

**To Reproduce**
Install snappi in python2.7

**Expected behavior**
Installation shall not fail

**Additional context**
Can be fixed by applying the python2.7 filter on the grpio==0.1.39 and grpcio-tools==0.1.39 and for python3 shall pic latest versions

**Comment by ankur-sheth** [comment]
@Rangababu-R @ANISH-GOTTAPU is still this valid?

**Comment by Rangababu-R** [comment]
This was already fixed Will close it.
available in 0.1.45
