### ISSUE TITLE
[Python] Add support for external grpc client

### ISSUE THREAD

**Issue by alakendu** [open-traffic-generator/openapiart#331]
**Is your feature request related to a use case? Please describe.**
Current implementation we provide location to create grpc channel. But user may want their own grpc connection and use that at the time of other API call

**Describe the solution you'd like**
We already provide similar solution for go ( https://github.com/open-traffic-generator/openapiart/issues/328)
Please extend that for python as well.

**Describe alternatives you've considered**
No

**Additional context**
Nil

**Comment by Rangababu-R** [comment]
@alakendu can this be closed?

**Comment by alakendu** [comment]
@Rangababu-R it's done. I have closed it
