### ISSUE TITLE
Support for find helper on iterators

### ISSUE THREAD

**Issue by ASHNA-AGGARWAL-KEYSIGHT** [open-traffic-generator/openapiart#342]
We need to implement a helper on iterators. 

Below is the suggestion:

1.  Instead of having multiple helpers for iterators, we can have a single generic function i.e findByProperty which will accept two attributes: propertName & propertyValue
2. PropertyName can be the property name for which value needs to be searched eg: name, location and it will be the string.
3. PropertyValue: value needs to search for that property, can be a string or regexp

Example:

`tx_port, rx_port = config.ports.port(name='Tx Port').port(name='Tx Port2')`
`config.ports.findByProperty("name", 'Tx Port')`

**Comment by Rangababu-R** [comment]
1. Search shall not confine to only string type. it must take all primitive types
2. Search should always result in list of matching objects.
3. I think search shall always take property parameter as mandatory argument. So, instead of findByProperty it shall be renamed to filter or search.

```
    ex:
        config.IterObject.filter("strType", "some_name_string")
        config.IterObject.filter("intType", 100)
        config.IterObject.filter("floatType", 100.01)
        config.IterObject.filter("boolType", True)
        config.IterObject.filter("boolType", False)

        metrics.IterObject.filter.hasvalue("property", ["value1", "value2", "value3"])
        metrics.IterObject.filter.greaterthan("property", 100)
        metrics.IterObject.filter.lessthan("property", 100)
        metrics.IterObject.filter.range("property", 0, 100)
        metrics.IterObject.filter.regex("property", r"ab?c_1\d+")
```
See the requirement in DB search dimension you will be able to figure out some more useful helper functions

**Comment by ASHNA-AGGARWAL-KEYSIGHT** [comment]
@ajbalogh Could you please review the proposal for adding helpers on iterators:

1. User can find the object through filter API which takes property parameter as a mandatory argument.
`metrics.IterObject.filter.equalsTo("property", search_value) `
2. Filter can accept the below helpers:
	a. equalsTo
	b. startsWith
	c. contains
	d. any
	e. greaterthan
	f. lessthan
	g. range
	h. regex
	i. null  --> to get the object if the property has no value
	j. notNull  --> to get the object if the property has a value

**Comment by ajbalogh** [comment]
Like the filter (is it required? you have an IterObject which is a list can the options be a part of it>) - like the options how about starting with equalTo unless there are other use cases/requests?

**Comment by ashutshkumr** [comment]
Closed in favor of https://github.com/open-traffic-generator/openapiart/issues/200
