### ISSUE TITLE
Optional arguments in Go SDK

### ISSUE THREAD

**Issue by ashutshkumr** [open-traffic-generator/openapiart#67]
This is the general pattern used in go to allow optional arguments. We should use this pattern and remove hard coded parameters in generated code.

```go
type Opts struct {
	httpServer         string
	debug              bool
}

func NewClient(opts *Opts) (*ApiClient, error) {
        if opts == nil {
                // defaults
                opts = &Opts{httpServer: "https://localhost", debug: true}
        }
        // rest of the code
}

func main() {
        // defaults
        api, err := NewClient()
        // non-defaults
        api, err := NewClient(&Opts{httpServer: "https://192.168.0.1", debug: false})
}

```

**Comment by ajbalogh** [comment]
I realize that this is the general pattern but i disagree with it.
With the ux pattern being proposed everything comes from the top level object without having to expose extra structures.

**Comment by ajbalogh** [comment]
updated comment with additional edits

________________________________

**Comment by ajbalogh** [comment]
This issue can be reopened in the future if we decide to extend the ux with public struct initialization on top of the fluent interface.

**Comment by ashutshkumr** [comment]
agreed, i almost missed this part.
