### ISSUE TITLE
protoc error while generating package in dev environment

### ISSUE THREAD

**Issue by PrasenjitAdhikary** [open-traffic-generator/openapiart#75]
This issue is noticed while generating in my dev environment:
Shown to @Rangababu-R 

Installed dependencies:
go get google.golang.org/protobuf/cmd/protoc-gen-go
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
go get golang.org/x/tools/cmd/goimports

Path to Go binary:
:/usr/local/go/bin:/home/<user>/go/bin

Error logs:
Generating python grpc stubs: /home/padhikary/workspace/athena/openapiart/.env/bin/python -m grpc_tools.protoc --python_out=/home/padhikary/workspace/athena/openapiart/art/sanity --grpc_python_out=/home/padhikary/workspace/athena/openapiart/art/sanity --proto_path=/home/padhikary/workspace/athena/openapiart/art sanity.proto
Generating go stubs: protoc --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --go_out=/home/padhikary/workspace/athena/openapiart/pkg/sanity --go-grpc_out=/home/padhikary/workspace/athena/openapiart/pkg/sanity --proto_path=/home/padhikary/workspace/athena/openapiart/art --experimental_allow_proto3_optional sanity.proto
protoc-gen-go: program not found or is not executable
Please specify a program using absolute path or make sure the program is available in your PATH system variable
--go_out: protoc-gen-go: Plugin failed with status code 1.
Traceback (most recent call last):
  File "artifacts.py", line 41, in <module>
    create_openapi_artifacts(openapiart_class)
  File "artifacts.py", line 22, in create_openapi_artifacts
    openapiart_class(
  File "/home/padhikary/workspace/athena/openapiart/openapiart/openapiart.py", line 53, in __init__
    self._generate()
  File "/home/padhikary/workspace/athena/openapiart/openapiart/openapiart.py", line 154, in _generate
    subprocess.check_call(process_args, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['protoc', '--go_opt=paths=source_relative', '--go-grpc_opt=paths=source_relative', '--go_out=/home/padhikary/workspace/athena/openapiart/pkg/sanity', '--go-grpc_out=/home/padhikary/workspace/athena/openapiart/pkg/sanity', '--proto_path=/home/padhikary/workspace/athena/openapiart/art', '--experimental_allow_proto3_optional', 'sanity.proto']' returned non-zero exit status 1.

**Comment by ashutshkumr** [comment]
https://github.com/open-traffic-generator/openapiart/pull/91
