### ISSUE TITLE
SetConfig response is always error in go sdk generated file

### ISSUE THREAD

**Issue by ANISH-GOTTAPU** [open-traffic-generator/openapiart#79]
SetConfig response is always error in go sdk generated file
Responses need to be generated.
Responses need to be added to return values for generated rpc methods.

**Comment by ajbalogh** [comment]
I would like to change the generation of proto responses to the following in order to be consistent with other messages.
The different status codes should be generated as a choice enum.

```proto
message StatusCode200 {
  bytes bytes = 1;
}
message StatusCode400 {
  ErrorDetails error_details = 1;
}
message StatusCode500 {
  Error error = 1;
}
message SetConfigResponse {
  message Choice {
    enum Enum {
      unspecified = 0;
      status_code_200 = 1;
      status_code_400 = 2;
      status_code_500 = 3;
    }
  }
  Choice.Enum choice = 1;
  optional StatusCode200 = 2;
  optional StatusCode400 = 3;
  optional StatusCode500 = 4;
}
```

**Comment by ashutshkumr** [comment]
Agree with this approach.

**Comment by ashutshkumr** [comment]
@ajbalogh removed oneof but not keeping choices. Might want to add them later.

Moreover,
- GRPC response stubs will be fixed (will return correct response apart from errors)
- Anish needs to fix in the same branch the pytest for streaming capture (since streaming response is removed)
