### ISSUE TITLE
f-string not supported python2.7

### ISSUE THREAD

**Issue by Rangababu-R** [open-traffic-generator/openapiart#82]
f-strings are support only from python3.6+ and not supported in python2.7.
failing the build in snappi.

**Comment by ajbalogh** [comment]
Coding to python 2.7 is not an option as the version is at end of life as of 2020.

**Comment by ajbalogh** [comment]
if 2.7 support is required then recommend changing f strings to keyword format.

```python
'Foo is {age} {units} old'.format(age=age, units=units)
```
